# Generated by Django 5.2.1 on 2025-06-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='payment_system',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='registration_cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='registration_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='registration_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='registration_nid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='registration_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
